### ISSUE TITLE
Mobile Platform: Dependency upgrades

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1892]
Time Tracking: MA-95

This is done when:
- [x] Package barcode_widget upgraded (PR #1876)
- [x] Package barcode_widget upgrade testing PASS in QA

- [x] Package dots_indicator upgraded (PR #1883)
- [x] Package dots_indicator upgrade testing PASS in QA

- [x] Package encrypt upgraded (PR #1885)
- [x] Package encrypt upgrade testing PASS in QA
